window.BloomGame = window.BloomGame || {};

BloomGame.LevelConfig = [
    // Level 1: Remember
    {
        level: 1,
        bloomLevel: 'Remember',
        bloomLabel: 'Knowledge',
        title: 'First Day',
        studentCount: 6,
        rows: 2,
        cols: 3,
        decayRate: 3.5,
        duration: 60,
        attentionThreshold: 50,
        powerupFrequency: 4,
        techniques: ['recall_prompt'],
        studentTypes: { normal: 5, eager: 1 },
        hasStations: false,
        hasLinks: false,
        hasQuestions: false,
        hasProjectBoard: false,
        hasPodium: false,
        introKey: 'level1_intro',
        outroKey: 'level1_outro',
    },
    // Level 2: Understand
    {
        level: 2,
        bloomLevel: 'Understand',
        bloomLabel: 'Comprehension',
        title: 'Making Sense',
        studentCount: 8,
        rows: 2,
        cols: 4,
        decayRate: 3.5,
        duration: 75,
        attentionThreshold: 55,
        powerupFrequency: 4,
        techniques: ['recall_prompt', 'explain'],
        studentTypes: { normal: 5, eager: 1, distracted: 2 },
        hasStations: false,
        hasLinks: false,
        hasQuestions: false,
        hasProjectBoard: false,
        hasPodium: false,
        introKey: 'level2_intro',
        outroKey: 'level2_outro',
    },
    // Level 3: Apply
    {
        level: 3,
        bloomLevel: 'Apply',
        bloomLabel: 'Application',
        title: 'Hands On',
        studentCount: 10,
        rows: 2,
        cols: 5,
        decayRate: 3.5,
        duration: 80,
        attentionThreshold: 60,
        powerupFrequency: 4,
        techniques: ['recall_prompt', 'explain', 'guided_practice'],
        studentTypes: { normal: 6, eager: 1, distracted: 3 },
        hasStations: true,
        stationCount: 3,
        hasLinks: false,
        hasQuestions: false,
        hasProjectBoard: false,
        hasPodium: false,
        introKey: 'level3_intro',
        outroKey: 'level3_outro',
    },
    // Level 4: Analyze
    {
        level: 4,
        bloomLevel: 'Analyze',
        bloomLabel: 'Analysis',
        title: 'Breaking It Down',
        studentCount: 12,
        rows: 3,
        cols: 4,
        decayRate: 3.5,
        duration: 90,
        attentionThreshold: 65,
        powerupFrequency: 4,
        techniques: ['recall_prompt', 'explain', 'jigsaw'],
        studentTypes: { normal: 6, eager: 2, distracted: 2, social: 2 },
        hasStations: false,
        hasLinks: false,
        hasQuestions: false,
        hasProjectBoard: false,
        hasPodium: false,
        introKey: 'level4_intro',
        outroKey: 'level4_outro',
    },
    // Level 5: Synthesize
    {
        level: 5,
        bloomLevel: 'Synthesize',
        bloomLabel: 'Synthesis',
        title: 'Creative Direction',
        studentCount: 14,
        rows: 3,
        cols: 5,
        decayRate: 3.5,
        duration: 100,
        attentionThreshold: 70,
        powerupFrequency: 4,
        techniques: ['recall_prompt', 'explain', 'group_work'],
        studentTypes: { normal: 5, eager: 3, distracted: 3, social: 3 },
        hasStations: false,
        hasLinks: false,
        hasQuestions: true,
        questionInterval: 9000,
        hasProjectBoard: false,
        hasPodium: false,
        introKey: 'level5_intro',
        outroKey: 'level5_outro',
    },
    // Level 6: Evaluate
    {
        level: 6,
        bloomLevel: 'Evaluate',
        bloomLabel: 'Evaluation',
        title: 'The Final Lesson',
        studentCount: 16,
        rows: 4,
        cols: 4,
        decayRate: 3.5,
        duration: 120,
        attentionThreshold: 75,
        powerupFrequency: 4,
        techniques: ['recall_prompt', 'explain', 'guided_practice', 'compare_contrast', 'quick_answer', 'socratic_question', 'group_project', 'peer_teach'],
        studentTypes: { normal: 6, eager: 3, distracted: 4, social: 3 },
        hasStations: true,
        stationCount: 2,
        hasLinks: true,
        linkCount: 5,
        hasQuestions: true,
        questionInterval: 8000,
        hasProjectBoard: true,
        synthesisGoal: 2,
        hasPodium: true,
        presentGoal: 3,
        introKey: 'level6_intro',
        outroKey: null,
    },
];
