window.BloomGame = window.BloomGame || {};

BloomGame.Techniques = {
    recall_prompt: {
        id: 'recall_prompt',
        name: 'Recall Prompt',
        bloomLevel: 'Remember',
        description: 'Ask a quick recall question',
        type: 'single',
        key: 'SPACE',
        range: 60,
        cooldown: 1500,
        channelTime: 0,
        attentionBoost: 30,
        icon: 'question',
        color: 0x2A9D8F,
    },
    explain: {
        id: 'explain',
        name: 'Think Aloud',
        bloomLevel: 'Understand',
        description: 'Model your thinking to nearby students',
        type: 'aoe',
        key: 'E',
        range: 150,
        cooldown: 4500,
        channelTime: 0,
        attentionBoost: 30,
        icon: 'lightbulb',
        color: 0xE9C46A,
    },
    guided_practice: {
        id: 'guided_practice',
        name: 'Learning Station',
        bloomLevel: 'Apply',
        description: 'Send student to a learning station',
        type: 'directed',
        key: 'Q',
        range: 60,
        cooldown: 0,
        channelTime: 0,
        attentionBoost: 0,
        icon: 'clipboard',
        color: 0xE76F51,
    },
    jigsaw: {
        id: 'jigsaw',
        name: 'Jigsaw',
        bloomLevel: 'Analyze',
        description: 'Group students to learn together',
        type: 'group',
        key: 'Q',
        range: 60,
        cooldown: 30000,
        channelTime: 0,
        attentionBoost: 0,
        groupSize: 4,
        groupDuration: 15000,
        icon: 'puzzle',
        color: 0x9B59B6,
    },
    group_work: {
        id: 'group_work',
        name: 'Group Work',
        bloomLevel: 'Synthesize',
        description: 'Group nearby students to collaborate at a desk',
        type: 'group',
        key: 'Q',
        range: 60,
        cooldown: 30000,
        channelTime: 0,
        attentionBoost: 0,
        groupDuration: 15000,
        icon: 'puzzle',
        color: 0x9B59B6,
    },
    compare_contrast: {
        id: 'compare_contrast',
        name: 'Compare & Contrast',
        bloomLevel: 'Analyze',
        description: 'Spark discussion between linked students',
        type: 'link',
        key: '3',
        range: 60,
        cooldown: 3000,
        channelTime: 0,
        attentionBoost: 35,
        icon: 'arrows',
        color: 0x264653,
    },
    socratic_question: {
        id: 'socratic_question',
        name: 'Socratic Question',
        bloomLevel: 'Analyze',
        description: 'Answer with a deeper question',
        type: 'question_response',
        key: '5',
        range: 60,
        cooldown: 2000,
        channelTime: 2000,
        attentionBoost: 40,
        icon: 'think',
        color: 0x9B59B6,
    },
    quick_answer: {
        id: 'quick_answer',
        name: 'Quick Answer',
        bloomLevel: 'Analyze',
        description: 'Give a simple answer',
        type: 'question_response',
        key: '4',
        range: 60,
        cooldown: 1000,
        channelTime: 0,
        attentionBoost: 15,
        icon: 'check',
        color: 0x3498DB,
    },
    group_project: {
        id: 'group_project',
        name: 'Group Project',
        bloomLevel: 'Synthesize',
        description: 'Send student to the project board',
        type: 'project',
        key: '6',
        range: 60,
        cooldown: 2000,
        channelTime: 0,
        attentionBoost: 15,
        icon: 'star',
        color: 0xE76F51,
    },
    peer_teach: {
        id: 'peer_teach',
        name: 'Peer Teaching',
        bloomLevel: 'Evaluate',
        description: 'Invite student to present',
        type: 'present',
        key: '7',
        range: 60,
        cooldown: 5000,
        channelTime: 0,
        attentionBoost: 0,
        icon: 'podium',
        color: 0xE9C46A,
    },
};
