window.BloomGame = window.BloomGame || {};

BloomGame.Techniques = {
    recall_prompt: {
        id: 'recall_prompt',
        name: 'Recall Prompt',
        bloomLevel: 'Remember',
        description: 'Ask a quick recall question',
        type: 'single',
        key: 'SPACE',
        range: 60,
        cooldown: 1500,
        channelTime: 0,
        attentionBoost: 30,
        icon: 'question',
        color: 0x2A9D8F,
    },
    explain: {
        id: 'explain',
        name: 'Explain',
        bloomLevel: 'Understand',
        description: 'Explain concept to nearby students',
        type: 'aoe',
        key: 'SPACE',
        range: 100,
        cooldown: 4000,
        channelTime: 1500,
        attentionBoost: 25,
        icon: 'lightbulb',
        color: 0xE9C46A,
    },
    guided_practice: {
        id: 'guided_practice',
        name: 'Guided Practice',
        bloomLevel: 'Apply',
        description: 'Send student to a task station',
        type: 'directed',
        key: 'E',
        range: 60,
        cooldown: 2000,
        channelTime: 0,
        attentionBoost: 10,
        icon: 'clipboard',
        color: 0xE76F51,
    },
    compare_contrast: {
        id: 'compare_contrast',
        name: 'Compare & Contrast',
        bloomLevel: 'Analyze',
        description: 'Spark discussion between linked students',
        type: 'link',
        key: 'E',
        range: 60,
        cooldown: 3000,
        channelTime: 0,
        attentionBoost: 35,
        icon: 'arrows',
        color: 0x264653,
    },
    socratic_question: {
        id: 'socratic_question',
        name: 'Socratic Question',
        bloomLevel: 'Analyze',
        description: 'Answer with a deeper question',
        type: 'question_response',
        key: '2',
        range: 60,
        cooldown: 2000,
        channelTime: 2000,
        attentionBoost: 40,
        icon: 'think',
        color: 0x9B59B6,
    },
    quick_answer: {
        id: 'quick_answer',
        name: 'Quick Answer',
        bloomLevel: 'Analyze',
        description: 'Give a simple answer',
        type: 'question_response',
        key: '1',
        range: 60,
        cooldown: 1000,
        channelTime: 0,
        attentionBoost: 15,
        icon: 'check',
        color: 0x3498DB,
    },
    group_project: {
        id: 'group_project',
        name: 'Group Project',
        bloomLevel: 'Synthesize',
        description: 'Send student to the project board',
        type: 'project',
        key: 'E',
        range: 60,
        cooldown: 2000,
        channelTime: 0,
        attentionBoost: 15,
        icon: 'star',
        color: 0xE76F51,
    },
    peer_teach: {
        id: 'peer_teach',
        name: 'Peer Teaching',
        bloomLevel: 'Evaluate',
        description: 'Invite student to present',
        type: 'present',
        key: 'E',
        range: 60,
        cooldown: 5000,
        channelTime: 0,
        attentionBoost: 0,
        icon: 'podium',
        color: 0xE9C46A,
    },
};
